/*
* Use the following array of objects to create your feed of messages. Copy the
* array into the `index.js` file generated by `create-react-app` and pass it
* down into App as a prop.
*/

let tweets = [
	{
		author: 'John Doe',
		content: 'Dinasaurs are soooooo cool!',
		likes: 8,
		retweets: 4,
		date: 'May 5, 2020'
	},
	{
		author: 'Jane Doe',
		content: 'I love learning about Dinasaurs!',
		likes: 11,
		retweets: 6,
		date: 'May 6, 2020'
	},
	{
		author: 'Adam Smith',
		content: 'Can\'t get enough of Dinasaurs!',
		likes: 15,
		retweets: 9,
		date: 'May 7, 2020'
	},
	{
		author: 'Sarah Smith',
		content: 'Dinasaurs are so fascinating!',
		likes: 7,
		retweets: 3,
		date: 'May 8, 2020'
	},
	{
		author: 'Chris Doe',
		content: 'Dinasaurs are the best!',
		likes: 12,
		retweets: 5,
		date: 'May 9, 2020'
	},
];
